# Generated by Django 5.0.4 on 2024-04-24 12:03

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="GA", max_length=2, verbose_name="Country"
            ),
        ),
    ]
