#!/bin/bash

set -o errexist

set -o pipefail

set -o nounset

postgres_ready() {
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}"
    )
execpt psycopg2.OperationalError:
    sys.exist(-1)
sys.exit(0)
END
}

until postgres_ready; do
>&2 echo "Waiting for PostgresSQL to become available...:-("
sleep 1
done
>&2 echo "PostgreSQL is ready!!!...:-)"

exec "$@"
